variables:
  DOTNET_SDK_IMAGE: mcr.microsoft.com/dotnet/sdk:8.0
  NUGET_PACKAGES_DIRECTORY: .nuget
  COMMON_PROJECT_PATH: src/Dictionary.Common/Dictionary.Common.csproj

stages:
  - build
  - publish

.restore_packages: &restore_nuget_packages
  - dotnet restore --packages $NUGET_PACKAGES_DIRECTORY

build:
  stage: build
  interruptible: true
  image: $DOTNET_SDK_IMAGE
  script:
    - *restore_nuget_packages
    - dotnet pack $COMMON_PROJECT_PATH --no-restore --configuration Release --output ./build
  cache:
    key: $CI_JOB_STAGE-$CI_COMMIT_REF_SLUG
    paths:
      - $NUGET_PACKAGES_DIRECTORY

publish:
  stage: publish
  when: manual
  interruptible: true
  image: $DOTNET_SDK_IMAGE
  script:
    - *restore_nuget_packages
    - dotnet pack $COMMON_PROJECT_PATH --no-restore --configuration Release --output ./build
    - dotnet nuget push "build/Slvpreview.Dictionary.Common.*.nupkg" --source https://api.nuget.org/v3/index.json --api-key $NUGET_API_KEY
